# Generated by Django 4.2.5 on 2023-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="chefhat.jpg", upload_to="%Y-%m-%d"),
        ),
    ]
