# Generated by Django 4.2.5 on 2023-10-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.TextField(null=True),
        ),
    ]
