# Generated by Django 4.2.5 on 2023-10-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
