# Generated by Django 4.2.5 on 2023-10-31 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_app", "0002_user_image_user_user_img"),
        ("account_app", "0003_alter_user_user_img"),
    ]

    operations = []
