# Generated by Django 4.2.5 on 2023-11-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_merge_20231031_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.TextField(null=True),
        ),
    ]
