# Generated by Django 4.2.5 on 2023-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_remove_userigrd_ingredients_igrd_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userigrd',
            name='igrd_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userigrd',
            name='user_id',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userigrd',
            name='user_igrd_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
