# Generated by Django 4.2.5 on 2023-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_userigrd_igrd_name_alter_userigrd_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userigrd',
            name='user_id',
            field=models.CharField(max_length=150),
        ),
    ]
