# Generated by Django 4.2.5 on 2023-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_alter_userigrd_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userigrd',
            name='user_igrd_date',
            field=models.DateField(),
        ),
    ]
