# Generated by Django 4.2.5 on 2023-10-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_no', models.IntegerField()),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField(null=True)),
                ('user_nick', models.CharField(max_length=50)),
                ('post_time', models.DateTimeField()),
                ('post_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('igrd_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('igrd_name', models.CharField(max_length=255)),
                ('igrd_content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topic', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('isDone', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_level', models.CharField(max_length=100, null=True)),
                ('cook_time', models.CharField(max_length=100, null=True)),
                ('ingredients', models.TextField()),
                ('direction', models.TextField()),
                ('recipe_img', models.TextField(null=True)),
                ('cooking_tips', models.TextField(null=True)),
                ('recipe_url', models.CharField(max_length=255, null=True)),
                ('importance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField()),
                ('post_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents_app.board')),
            ],
        ),
    ]
# Generated by Django 4.2.5 on 2023-10-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_no', models.IntegerField()),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField(null=True)),
                ('user_nick', models.CharField(max_length=50)),
                ('post_time', models.DateTimeField()),
                ('post_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('igrd_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('igrd_name', models.CharField(max_length=255)),
                ('igrd_content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_level', models.CharField(max_length=100, null=True)),
                ('cook_time', models.CharField(max_length=100, null=True)),
                ('serving', models.CharField(max_length=100, null=True)),
                ('ingredients', models.TextField()),
                ('direction', models.TextField()),
                ('recipe_img', models.TextField(null=True)),
                ('cooking_tips', models.TextField(null=True)),
                ('recipe_url', models.CharField(max_length=255, null=True)),
                ('importance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField()),
                ('post_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents_app.board')),
            ],
        ),
    ]
