# Generated by Django 4.2.5 on 2023-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='your_app_name_recipe',
        ),
    ]
