# Generated by Django 4.2.5 on 2023-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents_app', '0002_alter_recipe_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_level', models.CharField(max_length=100, null=True)),
                ('cook_time', models.CharField(max_length=100, null=True)),
                ('serving', models.CharField(max_length=100, null=True)),
                ('ingredients', models.TextField()),
                ('direction', models.TextField()),
                ('recipe_img', models.TextField(null=True)),
                ('cooking_tips', models.TextField(null=True)),
                ('recipe_url', models.CharField(max_length=255, null=True)),
                ('importance', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='contents_app_recipe',
        ),
    ]
