# Generated by Django 4.2.5 on 2023-10-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents_app', '0003_recipes_alter_recipe_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_no', models.IntegerField()),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField(null=True)),
                ('user_nick', models.CharField(max_length=50)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('post_like', models.IntegerField(default=0)),
                ('board_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents_app.board')),
            ],
        ),
    ]
