# Generated by Django 4.2.5 on 2023-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents_app', '0006_alter_board_board_no_alter_board_post_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
