# Generated by Django 4.2.5 on 2023-10-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents_app', '0007_alter_board_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='post_hit',
            field=models.IntegerField(default=0),
        ),
    ]
